### ISSUE TITLE
How to Remove the 5 famous people faces? 

### ISSUE THREAD

**Issue by Wulanpanekenan** [pillarpond/face-recognizer-android#15]
How to remove the 5 famous people faces so just have my face can detect?
thankyou

**Comment by pillarpond** [comment]
Push empty data, label files on "/sdcard/facerecognizer" in your device.

**Comment by Wulanpanekenan** [comment]
Thankyou it's working !
I want to ask something , how many face can we add as reference ?

**Comment by Wulanpanekenan** [comment]
I mean, the limit face can we add ?
Thankyou

**Comment by Wulanpanekenan** [comment]
and where is my picture save as a reference ? is it in my memory or ?
Thankyou and sorry for too many ask.

**Comment by pillarpond** [comment]
1) There is no limit. but inference time depends on number of faces. 
2) Internal or external storage in your device.

**Comment by Wulanpanekenan** [comment]
Okay thankyouu very much it's very helpfull

**Comment by puduliu** [comment]
I Pushed empty data, label files on "/sdcard/facerecognizer" in my device,but is not used.Whether to delete model data？
Thanks!
