### ISSUE TITLE
Can we decrease this training data time or any possibility to migrate this libsvm to latest version ?

### ISSUE THREAD

**Issue by AmitPrajapati1902** [pillarpond/face-recognizer-android#16]
I'm working of demo project, i have spend few hour to understand this demo, its really working nice.

I have few question with you.
1) Can we decrease training data time ?
2) Can we migrate this libsvm with latest version Version 3.23 or it is not possible in this code.

It would be nice if you answer this.

Thanks in advance.

**Comment by pillarpond** [comment]
1. Please reduce size of training image.  
2. Maybe yes. but I'm not sure.
