### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by thekingrenz23** [pillarpond/face-recognizer-android#17]
Build command failed.

OS: Linux Mint 18

`Error while executing process /home/razer/Desktop/android-sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target tensorflow_demo}
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razer/Desktop/face-recognizer-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a

ninja: error: manifest 'build.ninja' still dirty after 100 tries`

**Comment by MaulyGabriel** [comment]
see this link https://travis-ci.org/pillarpond/face-recognizer-android
