### ISSUE TITLE
Recognition Results

### ISSUE THREAD

**Issue by aamir497** [pillarpond/face-recognizer-android#18]
As the number of classes increases the match prob decreased. Like i register 10 people the results are perfect. But when it goes to 15 or more people the match prob results decreases. For 10 classes the average prob result is .67 for each. But for 15 or more the prob result reduces to 0.35 or less. How can i solve this.

**Comment by pillarpond** [comment]
Sum of all probs is 1.
So, prob is in inverse proportion to number of people.

You can consider changing threshold value.
https://github.com/pillarpond/face-recognizer-android/blob/master/app/src/main/java/pp/facerecognizer/Classifier.java#L176
