### ISSUE TITLE
Use Front Camera 

### ISSUE THREAD

**Issue by leecpsg** [pillarpond/face-recognizer-android#20]
Hi,

When using front camera, the tracking goes opposite direction.
Where to change to make this right?

Thanks.

**Comment by pillarpond** [comment]
Check the orientation.
https://github.com/pillarpond/face-recognizer-android/blob/master/app/src/main/java/pp/facerecognizer/MainActivity.java#L148

**Comment by rahulsharmagbpec** [comment]
@pillarpond i guess the answer doesn't match with the problem.

**Comment by pingnuttakrid** [comment]
@pillarpond  how you solve it?

**Comment by iot-hunter** [comment]
@leecpsg  have you solve it I need your help
