### ISSUE TITLE
What is the difference between the model and data file?

### ISSUE THREAD

**Issue by sepehr78** [pillarpond/face-recognizer-android#22]
I wanted to get rid of the 5 famous people so I erased the contents of the data and label files. However it seems that the model file is also affected by training, because each time I train a new face the contents of the model file change. So how can I "reset" the model file so it does not contain any numbers/data related to the 5 famous people. Or is the model file not related to face recognition but rather face detection?

Thanks in advance.

**Comment by pillarpond** [comment]
When training with new data file, the model file will be overwritten.
So you don't need to delete a model file.
