### ISSUE TITLE
Classifier does not work with non-square face size

### ISSUE THREAD

**Issue by sepehr78** [pillarpond/face-recognizer-android#23]
When initializing the classifier using
`         classifier = Classifier.getInstance(getAssets(), height, width);
`
giving unequal width and height causes the app to crash when it tries to perform facial recognition. I was wondering why this occurs.

**Comment by pillarpond** [comment]
The file is changed now.
But if you want to change input size, you must resize input tensor before inference.
```java
interpreter.resizeInput(0, new int[]{1, height, width, 3});
```
