### ISSUE TITLE
About the App

### ISSUE THREAD

**Issue by apresswala52** [pillarpond/face-recognizer-android#27]
Heyy,
Im currently in final year of Engineering, went through your repo and we are developing a similar application. It would be great if you could guide us as to how you built the entire application. Any help from your side, will be appreciated. Any links, blogs, papers that could be refernced???
Thank You.

**Comment by pillarpond** [comment]
Please refer to below links.

* Facenet ([Paper](https://arxiv.org/abs/1503.03832), [Github](https://github.com/davidsandberg/facenet))
* BlazeFace ([Paper](https://arxiv.org/abs/1907.05047), [Site](https://sites.google.com/view/perception-cv4arvr/blazeface))
