### ISSUE TITLE
OnTrackListener()?

### ISSUE THREAD

**Issue by tabish075** [pillarpond/face-recognizer-android#29]
Hi, thanks for your work, is there a tracking listener so when a user is identified i can do stuff ??

**Comment by pillarpond** [comment]
Unfortunately, there is no tracking listener.
You can refer to [this code](https://github.com/pillarpond/face-recognizer-android/blob/383acefe09b32032347fad67733a8509aa8b821e/app/src/main/java/pp/facerecognizer/Recognizer.java#L147).
