### ISSUE TITLE
How to make tensorflow lite file

### ISSUE THREAD

**Issue by vihari1729** [pillarpond/face-recognizer-android#32]
Dear pillarpond

Could you elaborate the making of tensorflow lite from frozen file for face recognition using facenet model

**Comment by jaiminajmeri** [comment]
Check this if its of any help.
https://github.com/tensorflow/tensorflow/issues/19431#issuecomment-467013566

**Comment by vihari1729** [comment]
@jaiminajmeri The inference graph that will be produced (using the link you mentioned) corresponds to the pre-trained Facenet Protobuf file. If I want to deploy TFlite model on a Android, it has to be trained on the training images I provide; which means I need a Tflite version of the trained model.My actual question is, How can a pretrained model's .pb , converted to tflite version, will be used to predict my data?

**Comment by jaiminajmeri** [comment]
Can you confirm my understanding?

So, you already have a trained model for your dataset which is in '.pb' format, you just need to convert it into '.tflite' model to run on Android for predicting?

If this is true, may I know which model have you used for training? is it `Inception ResNet v1`? Or have you trained for classification?

**Comment by vihari1729** [comment]
@jaiminajmeri I don't have trained model for my dataset which is in .pb format.

The tflite model that will be produced (https://github.com/tensorflow/tensorflow/issues/19431) corresponds to the pre-trained Facenet Protobuf file. If I want to deploy TFlite model on a Android, it has to be trained on the training images I provide; which means I need a Tflite version of the trained model.
My question is How can a pretrained model's .pb , converted to tflite version, will be used to predict my data in inference?

**Comment by jaiminajmeri** [comment]
@vihari1729, I am beginner in ML. The steps for generating `tflite` after you have trained your model may still remain the same I think, the variation might be in the parameters for generating it. Have you tried it? any errors?
