### ISSUE TITLE
data&model

### ISSUE THREAD

**Issue by karthikeyankumarasamy** [pillarpond/face-recognizer-android#5]
Hi, i use your files and it will working well on your trained class.when i use my own graph trained using facenet-davidsandberg code.if i use your data&model files for my graph it seems like my trained images are unknown. so please tell me how do you create your data,model and mtcnn files.

thanks in advance

**Comment by Ashing00** [comment]
I have the same problem ,I only got  .pkl file，and I don't know how to transfer the .pkl file to your android file data or model  ?

**Comment by pillarpond** [comment]
1) data file

Please change code in [facenet-davidsandberg](https://github.com/davidsandberg/facenet/blob/master/src/classifier.py#L102).

from
```python
with open(classifier_filename_exp, 'wb') as outfile:
    pickle.dump((model, class_names), outfile)
```
to
```python
with open('data', 'w') as outfile:
    for i in range(len(labels)):
        outfile.write('%d' % labels[i])
        for j in range(len(emb_array[i])):
            outfile.write(' %d:%f' % (j, emb_array[i][j]))
        outfile.write('\n')
```

2) model file

And then you can make model file using below code.
```python
from svmutil import *
y, x = svm_read_problem('data')
m = svm_train(y, x, '-t 0 -b 1')
svm_save_model('model', m)
```

**Comment by Ashing00** [comment]
Pillarpond, 
       thank you,now I can create data and model files.
      but when I replaced original files with my data/model/label files
     I meet APP crash issue when initialize...
     I will study more ,thank you.

**Comment by Ashing00** [comment]
Pillarpond,
    now I can use mydata to detect and recognize face,but I found 2 problem.
    1.I found if change data/model/label  files  in FileUtils.java to data_1/model_1/label_1
       I meet APP crash issue when initialize...
     2.when change data/model/label files to my new data/model/label files need to manually clear
        these old files in Cell phone ，it means when I build APK with these files and re-install APK to cell  phone ,these files can not be upgraded  automatically.
      
     Anyway,thank you again ,it is a good APP example.

**Comment by anupamjuit** [comment]
I can create data and model files. Is there any way to create label too by code.
Thank you in advance.

**Comment by phuhung273** [comment]
@pillarpond Thank you so much for your helpful repo.

I have followed your guide to create model and data file. But how about the label file ?

I'm doing it in a manual way. But with large dataset this is not possible
