### ISSUE TITLE
Actual test, new characters, code recognition seems to have some problems, if you use the default item, the recognition is no problem,

### ISSUE THREAD

**Issue by mmabluesky** [pillarpond/face-recognizer-android#9]
，

**Comment by oopsodd** [comment]
Could you please explain more details about your problem?

**Comment by mmabluesky** [comment]
@oopsodd 
nothing ,thank you ,I will close this

**Comment by oopsodd** [comment]
The app recognizes wrong when I add new person. How did you fix that? @mmabluesky
